adp:
  target: warehouse
  outputs:
    warehouse:
      type: fabric
      authentication: CLI
      driver: ODBC Driver 18 for SQL Server
      host: "{{ env_var('FABRIC_WAREHOUSE_HOST') }}"
      database: "{{ env_var('FABRIC_WAREHOUSE_DATABASE') }}"
      schema: "{{ env_var('FABRIC_WAREHOUSE_SCHEMA') }}"
      threads: 4