adp:
  target: warehouse
  outputs:
    warehouse:
      type: fabric
      authentication: environment
      driver: ODBC Driver 18 for SQL Server
      host: bkjr54bowwyufnypvcecwxiehm-bc4mnoc7clxernfcsk5res6txq.datawarehouse.fabric.microsoft.com
      database: adp_warehouse
      schema: dbo

      threads: 4
