version: 2

model:
  - name: stg_patients
    description: "Staging table for patient data."
    columns:
      - name: patient_id
        description: "Unique identifier for each patient."
      - name: name
        description: "Full name of the patient."
      - name: date_of_birth
        description: "Date of birth of the patient."
  
  - name: patients 
    description: "Transformed patient data."
    columns:
      - name: patient_id
        description: "Unique identifier for each patient."
      - name: name
        description: "Full name of the patient."
      - name: date_of_birth
        description: "Date of birth of the patient."