version: 2

sources:
  - name: adp_lakehouse_raw
    schema: adp_lakehouse_raw          # Exact schema name for Fabric Spark
    tables:
      - name: raw_patients
        description: "Raw lung cancer patient risk factors and severity data"
        columns:
          - name: patient_id
            description: "Unique patient identifier like P1, P100"
            tests:
              - unique
              - not_null

          - name: age
            tests:
              - not_null

          - name: gender
            tests:
              - not_null

          - name: level
            description: "Cancer severity: Low, Medium, High"
            tests:
              - not_null

          # Example for risk factor columns (1-8 or 1-9 scale)
          - name: air_pollution
            tests:
              - not_null