version: 2

sources:
  - name: raw
    database: adp_lakehouse
    schema: raw          # Exact schema name for Fabric Spark
    tables:
      - name: fhir_patients
        description: "Raw patients"
        columns:
          - name: patient_id
            description: "Unique patient identifier like P1, P100"